version: '3.9'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - type: bind
        source: ../
        target: /var/www
    networks:
      - ersnet
  nginx:
    build:
      context: ./docker/nginx
    volumes:
        #Nginx Global Configurations
      - type: bind
        source: ./docker/nginx/nginx.conf
        target: /etc/nginx/nginx.conf

      - type: bind
        source: ./docker/nginx/conf.d/
        target: /etc/nginx/conf.d

      - type: bind
        source: ./sites/ers.test/site.conf
        target: /etc/nginx/sites-available/ers.test.conf

      - type: bind
        source: ./sites/ers.test/certificates/
        target: /etc/nginx/sites/ers.test/certificates

      - type: bind
        source: ./sites/ers.test/logs/error.log
        target: /var/log/nginx/error.log

      - type: bind
        source: ../
        target: /var/www

    ports:
      - "80:80"
      # Uncomment if using HTTPS/SSL certificates
      - "443:443"
    depends_on:
      - php-fpm
    restart: always
    networks:
      - ersnet
  # Database
  database:
    build:
      context: ./docker/mysql
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 

      - type: bind
        source: ./docker/mysql/data/
        target: /var/lib/mysql

      - type: bind
        source: ./docker/mysql/log/
        target: /var/log/mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitnami_opencart
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - ersnet

networks:
  ersnet:
    driver: bridge
