version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
        # Mount PHP for each Public folder:

        # ers.test:
        # - Public Folder:
      - ../:/var/www
    networks:
      - ersnet

  nginx:
    build:
      context: ./docker/nginx
    volumes:
        #Nginx Global Configurations
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d

        #Nginx Configurations for you Sites:
        # ers.test:
        # - Nginx Server block
      - ./sites/ers.test/site.conf:/etc/nginx/sites-available/ers.test.conf
        # - Cloudflare certificates, uncomment if using certificates / ssl (see ers.test/site.conf):
      - ./sites/ers.test/certificates/:/etc/nginx/sites/ers.test/certificates
      - ./sites/ers.test/logs/error.log:/var/log/nginx/error.log
        # - Public Folder:
      - ../:/var/www

    ports:
      - "80:80"
      # Uncomment if using HTTPS/SSL certificates
      - "443:443"
    depends_on:
      - php-fpm
    restart: always
    networks:
      - ersnet
      

  # Database
  database:
    build:
      context: ./docker/mysql
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ./docker/mysql/data/:/var/lib/mysql
      - ./docker/mysql/log/:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitnami_opencart
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - ersnet

networks:
  ersnet:
    driver: bridge
