version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
        # Mount PHP for each Public folder:

        # localhost.test:
        # - Public Folder:
      - ./sites/localhost.test/root/public/:/var/www/localhost.test/public

        # site-two.com:
        # - Public Folder:
      #- ./sites/site-two.com/root/public/:/var/www/site-two.com/public

    networks:
      - netwrokname

  nginx:
    build:
      context: ./docker/nginx
    volumes:
        #Nginx Global Configurations
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d

        #Nginx Configurations for you Sites:

        # localhost.test:
        # - Nginx Server block
      - ./sites/localhost.test/site.conf:/etc/nginx/sites-available/localhost.test.conf
        # - Cloudflare certificates, uncomment if using certificates / ssl (see localhost.test/site.conf):
      - ./sites/localhost.test/certificates/:/etc/nginx/sites/localhost.test/certificates
        # - Public Folder:
      - ./sites/localhost.test/root/public/:/var/www/localhost.test/public

        # site-two.com:
        # - Nginx Server block
      #- ./sites/site-two.com/site.conf:/etc/nginx/sites-available/site-two.com.conf
        # - Cloudflare certificates, uncomment if using certificates / ssl (see localhost.test/site.conf):
      #- ./sites/site-two.com/certificates/:/etc/nginx/sites/site-two.com/certificates
        # - Public Folder:
      #- ./sites/site-two.com/root/public/:/var/www/site-two.com/public
    ports:
      - "80:80"
      # Uncomment if using HTTPS/SSL certificates
      - "443:443"
    depends_on:
      - php-fpm
    restart: always
    networks:
      - netwrokname

  # Database
  database:
    build:
      context: ./docker/mysql
    restart: 'always'
    ports:
      - "127.0.0.1:3306:3306"
    volumes: 
      - ./docker/mysql/data/:/var/lib/mysql
      - ./docker/mysql/log/:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_name
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - netwrokname

networks:
  netwrokname:
    driver: bridge
